site_name: EmotionCF
site_description: "A Python package to perform collaborative filtering on emotion datasets"
site_url: "https://cosanlab.github.io/emotionCF"
repo_url: "https://github.com/cosanlab/emotionCF"
repo_name: "cosanlab/emotioncf"
theme:
  name: material
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight
nav:
  - Home: index.md
  - Tutorials:
      - 1) Working with Dense Data: examples/dense-data
      - 2) Working with Sparse Data: examples/sparse-data
      - 3) Working with Time-Series: examples/timeseries-data
  - Contributing to Development: development.md
  - API Reference:
      - emotioncf.utils: api/utils.md
      - emotioncf.base: api/base.md
      - emotioncf.models:
          - Mean: api/mean.md
          - KNN: api/knn.md
          - NNMF_mult: api/nmf_m.md
          - NNMF_sgd: api/nmf_s.md
plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            inherited_members: True
          filters:
            - "^__init__$"
          rendering:
            show_source: true
            show_if_no_docstring: False
            show_root_toc_entry: True
            show_root_members_full_path: True
            show_category_heading: False
            heading_level: 4
      watch:
        - emotioncf
