name: (Auto-On-Release) PyPI Deploy

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    name: Build & deploy package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Wheel and source build
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
